### ISSUE TITLE
Plot_posterior_odds med_annot variable

### ISSUE THREAD

**Issue by teresa-mcgee** [wesleycrouse/bmediatR#5]
Can you please explain what the med_annot variable is?

**Comment by gkeele** [comment]
This plot visualizes mediation for candidates across the genome, and so med_annot is expected to include the genomic coordinate information for all candidates. Primarily it needs to include mediator ID, chromosome, and genomic coordinate (named middle).

Thanks for pointing out a serious gap in the documentation. The documentation has been expanded to provide more details.
