### ISSUE TITLE
Categorical Variable as Exposure

### ISSUE THREAD

**Issue by lizlitkowski** [wesleycrouse/bmediatR#6]
Hi -- I would like to use bmediatR in a situation where my exposure is a categorical variable representing 39 strains of mice.  Is that possible?  It seems like the expectation is to use a genotypes at the variant level.  Thanks.

**Comment by gkeele** [comment]
Hi. That should work in bmediatR. We were primarily focused on the case in which the initial variable was a genotype, but bmediatR can handle all types of design matrices. The first thing to do is convert the categorical treatment from being a factor column in a data.frame to a multi-column design matrix. Here is a little simulation example:
`
library(bmediatR)

## Simulations
# Simulate the design matrix for a categorical variable with 4 levels
set.seed(10)
trt <- sapply(1:39, function(i) sample(x = 1:4, size = 1))
X <- model.matrix(~ -1 + trt, data = data.frame(trt = factor(trt)))

# X -> m
beta_x <- c(0, 2, 4, 6)

# Simulate m from X
m <- X %*% beta_x + rnorm(n = 39)

# m -> y
beta_m <- 5

# Simulate y from m
y <- m * beta_m + rnorm(n = 39)

# Run bmediatR and plot
sim_bmediatR <- bmediatR(y = y, M = m, X = X)
plot_posterior_bar(sim_bmediatR, mediator_id = 1)
`

**Comment by lizlitkowski** [comment]
Thanks so much for this reply.  That seems to work!
