### ISSUE TITLE
Issues with the X matrix

### ISSUE THREAD

**Issue by jieeewu** [wesleycrouse/bmediatR#7]
Hi,
I would like to use the bmediatR package in human data and could you please tell me what information should be in the two columns of the X matrix, allele 1 and allele 2? After that, can I use the default parameters of the bmediatR function for analysis?

For example，
head(X)
#>               allele1 allele2
#> sample1         1       0
#> sample2         1       1
#> sample3         0       0
#> sample4         1       0
#> sample5         0       0

**Comment by gkeele** [comment]
Hi,

Yes, the X matrix you describe should work, though I can't tell if you are trying to model one or two SNPs. For one bi-allelic SNP where each column is an allele, each row should have exactly one "1". Whereas if it's two SNPs, you could reduce X to columns corresponding to one allele for each SNP.

Here is some example simulation code that sets up the X matrix for a single SNP, then simulates m and y, and finally, runs bmediatR:

`library(bmediatR)

# Simulate the design matrix for a bi-allelic SNP
set.seed(10)
snp <- sapply(1:100, function(i) sample(x = 0:1, size = 1))
X <- model.matrix(~ -1 + snp, data = data.frame(snp = factor(snp)))
colnames(X) <- c("allele1", "allele2")
rownames(X) <- paste0("sample", 1:100)

# X -> m
beta_x <- c(0, 1)

# Simulate m from X
m <- X %*% beta_x + rnorm(n = 100)

# m -> y
beta_m <- 2

# Simulate y from m
y <- m * beta_m + rnorm(n = 100)

# Run bmediatR and plot
sim_bmediatR <- bmediatR(y = y, M = m, X = X)
plot_posterior_bar(sim_bmediatR, mediator_id = 1)`

One thing to note is that you should make sure X, m, and y are aligned in terms of samples, ie, they have the same sample ordering.

If you meant two SNPs, then you should adjust the bmediatR() call to:
`
sim_bmediatR <- bmediatR(y = y, M = m, X = X, options_X = list(sum_to_zero = F, center = T, scale =T))
`

**Comment by jieeewu** [comment]
Thank you for your kind answer, I may not have expressed my question clearly, the example I gave is a SNP with 3 genotypes: 00/01/11, 00 means two alleles are REF allele, 11 means both alleles are ALT allele, according to your suggestion, "each row should have exactly one 1", then how should the genotype "11" be converted?

**Comment by gkeele** [comment]
I understand now. My simplified example for a single locus assumed that individuals were homozygous (or haploid) and thus not ideal for human data. It's fairly common to assume an additive model (counts of one of the alleles). Alternatively, each genotype could be modeled with its own effect. Each of these cases is possible with bmediatR. 

`library(dplyr)

set.seed(10)
snp <- sapply(1:100, function(i) sample(x = c("00", "01", "11"), size = 1))

# Additive X
X_add <- data.frame(genotype = snp) %>%
  mutate(count = case_when(genotype == "00" ~ 0,
                           genotype == "01" ~ 1,
                           genotype == "11" ~ 2)) %>%
  dplyr::select(count) %>%
  as.matrix
rownames(X_add) <- paste0("sample", 1:100)

# Full X
X_full <- model.matrix(~ -1 + snp, data = data.frame(snp = factor(snp)))
rownames(X_full) <- paste0("sample", 1:100)
colnames(X_full) <- c("genotype00", "genotype01", "genotype11")
`

Either of these design matrices could be input into bmediatR. X_add is assuming a simpler additive model. Note that if you wish to further simulate from either of these two cases (as in my previous example code), the genetic effects will differ. The additive model will assume a single scalar effect of having an additional copy of the allele (often parameterized to be the minor allele). For the full model, each genotype has its own effect, so something like c(0, 5, 20).
