### ISSUE TITLE
y_depends_x includes complete mediation 

### ISSUE THREAD

**Issue by erisemberg** [wesleycrouse/bmediatR#9]
In `return_preset_odds_index`, the `y_depends_x` class of models includes models `c(4:8, 11, 12)` (line 216 of bmediatR.R). ML4 is complete mediation with the X->y edge being absent, so should that be included in this model class?

**Comment by wesleycrouse** [comment]
Hi @erisemberg! Yes, this is correct. The `y_depends_x` group of models is intended to include any DAG in which there is information flowing from X to Y. Y depends on X marginally in the complete mediation case (i.e. Y is only independent of X conditionally on M), so `y_depends_x` includes complete mediation.

**Comment by erisemberginari** [comment]
That makes sense! Thanks!

**Comment by erisemberg** [comment]
That makes sense! Thanks!
